### ISSUE TITLE
Unneeded replacement in 0.7.0

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#185]
There is a regression in 0.7.0 of the provider. I'm using this example: https://github.com/pulumi/pulumi-google-native/blob/master/examples/functions-ts/index.ts

Repro:

1. Deploy the program.
2. Change the `main.py` of the function.
3. Run the preview

Expected result: blob is replaced, function is not replaced.
Current result: function is replaced too.

Apparently, this is caused by [this line](https://github.com/pulumi/pulumi-google-native/blob/e4096e85cc86df7b215503b9c2acaa064bb7a978/provider/pkg/provider/provider.go#L370) from #181. Although, I don't understand yet why adding `project,location` to the collection of replacement properties causes the engine to replace the function.

**Comment by fjgal** [comment]
@mikhailshilkov thanks for logging this issue, I believe I am experiencing this when using the google-native provider to deploy cloud functions. I also noticed that the function is deleted before being replaced, which makes the situation worse because it can cause downtime.

I noticed [this line of code](https://github.com/pulumi/pulumi-google-native/blob/e4096e85cc86df7b215503b9c2acaa064bb7a978/provider/pkg/provider/provider.go#L381)), that I suspect is causing the delete-before-replace

```go
return &rpc.DiffResponse{Changes: rpc.DiffResponse_DIFF_UNKNOWN, Replaces: replaces, DeleteBeforeReplace: true}, nil
```

any idea on when this issue will be addressed? I need to use the `secretEnvironmentVariables` property which is not (yet?) available in the google-classic provider
