### ISSUE TITLE
DNS v1 ResrouceRecordSet ignore deleteBeforeReplace

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-google-native#747]
### What happened?

I had to downgrade from dns/v2 to dns/v2 due to the [change made in 0.25](https://github.com/pulumi/pulumi-google-native/blob/master/CHANGELOG.md#0250-2022-09-01). I tried setting `deleteBeforeReplace` because GCP does not allow duplicate DNS entries (reasonable).

### Steps to reproduce

1. Create a `dns/v2/ResourceRecordSet`
2. Downgrade to a `dns/v1/ResourceRecordSet`

### Expected Behavior

The existing record is deleted.

### Actual Behavior

Pulumi tries to create the new record before deleting the old one.

### Output of `pulumi about`

```
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     x86_64

This project is written in nodejs: executable='/Users/kaoru/.asdf/shims/node' version='v16.14.2'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @KaoruDev! Unfortunately, in this case `deleteBeforeReplace` won't do the right thing because to the Pulumi engine, v1 and v2 RecordSets are different entities.

As a workaround, you might consider [aliases](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/#aliases) to alias v2 to v1.

You could also simply delete the existing v2 resource by removing it from your program and running `pulumi up`, or delete it in a more targeted way via `pulumi destroy -t <urn of old resource>`.

**Comment by KaoruDev** [comment]
>  v1 and v2 RecordSets are different entities.

Ahhh right right sorry I missed that.

> As a workaround, you might consider [aliases](https://www.pulumi.com/docs/intro/concepts/resources/options/aliases/#aliases) to alias v2 to v1.

Oh I didn't think this would work given they're different providers, I'll give that a shot.

> You could also simply delete the existing v2 resource by removing it from your program and running pulumi up, or delete it in a more targeted way via pulumi destroy -t <urn of old resource>.

Yeah this is something similiar to what I ended up doing.

Thanks for the quick response, I'll close.
