### ISSUE TITLE
Multiple paths to the same resource

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-google-native#92]
Discovery documents contain a hierarchy of resources. Two resources with the same name can be in multiple places of the tree: e.g. directly under `projects` and then again under `projects/location`. We pick a ~random one currently and build up the names of resources using parent names (except project/location/etc). Is that a valid strategy? Are those endpoints always equivalent? Any preference which one to use?

**Comment by tequilarista** [comment]
Could we get an explicit example of this?

**Comment by mikhailshilkov** [comment]
This happens for most resources. Random examples:

- NodePools [1](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/container_v1.json#L731) and [2](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/container_v1.json#L1903)
- Cloud Run Services [1](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/run_v1.json#L633) and [2](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/run_v1.json#L1446)
- Apigee attachments [1](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/apigee_v1.json#L2859) and [2](https://github.com/pulumi/pulumi-google-native/blob/e145c86bfdc4086336850fff17164ebd26eaa181/discovery/apigee_v1.json#L5851)

**Comment by codyoss** [comment]
> Container

I believe this is due to the project_id/zone resource pathing is [deprecated](https://github.com/googleapis/googleapis/blob/fe3cc5e650b8e52537f02549fe5fb49fc386f3a9/google/container/v1/cluster_service.proto#L1700-L1719).

> Cloud Run

This one is is a little different of an API because it is compatible with knative. If the namespace service create is used you need to use a regional endpoint. I believe the other api can be used with global endpoint since location is encoded into the url as a part of the parent. 

> Apigee

In that example it looks like attachments can be "attached" to different resource types. This seems valid to have both.

**Comment by mikhailshilkov** [comment]
Thank you @codyoss that were our conclusions too. I'll close the issue for now.
